export const CURRENCIES_NAMES = [
  { currency: 'USD', name: 'United States dollar' },
  { currency: 'PLN', name: 'Polish złoty' },
  { currency: 'EUR', name: 'Euro' },
  { currency: 'GBP', name: 'British Pound Sterling' },
  { currency: 'JPY', name: 'Japanese Yen' },
  { currency: 'BGN', name: 'Bulgarian Lev' },
  { currency: 'CZK', name: 'Czech koruna' },
  { currency: 'DKK', name: 'Danish Krone' },
  { currency: 'HUF', name: 'Hungarian Forint' },
  { currency: 'RON', name: 'Romanian Leu' },
  { currency: 'SEK', name: 'Swedish Krona' },
  { currency: 'CHF', name: 'Swiss Franc' },
  { currency: 'ISK', name: 'Icelandic Krona' },
  { currency: 'NOK', name: 'Norwegian Krone' },
  { currency: 'TRY', name: 'Turkish Lira' },
  { currency: 'AUD', name: 'Australian Dollar' },
  { currency: 'BRL', name: 'Brazilian Real' },
  { currency: 'CAD', name: 'Canadian Dollar' },
  { currency: 'CNY', name: 'Chinese Yuan' },
  { currency: 'HKD', name: 'Hong Kong Dollar' },
  { currency: 'IDR', name: 'Indonesian Rupiah' },
  { currency: 'ILS', name: 'Israeli Shekel' },
  { currency: 'INR', name: 'Indian Rupee' },
  { currency: 'KRW', name: 'South Korean Won' },
  { currency: 'MXN', name: 'Mexican Peso' },
  { currency: 'MYR', name: 'Malaysian Ringgit' },
  { currency: 'NZD', name: 'New Zealand Dollar' },
  { currency: 'PHP', name: 'Philippine Peso' },
  { currency: 'SGD', name: 'Singapore Dollar' },
  { currency: 'THB', name: 'Thai Baht' },
  { currency: 'ZAR', name: 'South African Rand' }
];

export const CURRENCIES = CURRENCIES_NAMES.map((currency) => currency.currency);

export const REQUEST_CATEGORIES = [
  "Other",
  "Electronics & Gadgets",
  "Fashion & Accessories",
  "Home & Living",
  "Health & Beauty",
  "Food & Beverages",
  "Art & Collectibles",
  "Automotive & Parts",
  "Tools & Equipment",
  "Graphic Design",
  "Web & App Development",
  "Writing & Translation",
  "Video Editing",
  "Marketing & Advertising",
  "Virtual Assistance",
  "Business Consulting",
  "Legal & Financial Services",
  "Custom Art",
  "Music Production",
  "Voiceover",
  "3D Modeling",
  "Animation",
  "Photography",
  "Crafts & DIY Projects",
  "Manufacturing",
  "Wholesale Suppliers",
  "Logistics & Shipping",
  "Event Planning",
  "Corporate Training",
  "Market Research",
  "SaaS Solutions",
];